apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-express-root-username: dXNlcm5hbWU=
  mongo-express-root-password: cGFzc3dvcmQ=